apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: node-express-app:apps/Deployment:default/node-express-deployment
    deployment.kubernetes.io/revision: "11"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"node-express-app:apps/Deployment:default/node-express-deployment"},"name":"node-express-deployment","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"node-express"}},"template":{"metadata":{"labels":{"app":"node-express"}},"spec":{"containers":[{"image":"monta2027/node-express:latest","name":"node-app","ports":[{"containerPort":3000}],"resources":{"limits":{"cpu":"1","memory":"512Mi"}}}]}}}}
  creationTimestamp: "2025-07-29T11:40:12Z"
  generation: 12
  name: node-express-deployment
  namespace: default
  resourceVersion: "77410"
  uid: 6e3140dd-0ad6-4eb7-a3c5-5339053513e1
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: node-express
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-07-29T14:13:31+01:00"
      creationTimestamp: null
      labels:
        app: node-express
    spec:
      containers:
      - image: monta2027/node-express:latest
        imagePullPolicy: Always
        name: node-app
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: "300m"
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2025-07-29T16:36:14Z"
    lastUpdateTime: "2025-07-29T16:36:14Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-29T16:49:36Z"
    lastUpdateTime: "2025-07-29T16:49:38Z"
    message: ReplicaSet "node-express-deployment-5c8b887d97" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 12
  readyReplicas: 3
  replicas: 4
  unavailableReplicas: 1
  updatedReplicas: 1
