image:
  repository: monta2027/node-express
  tag: latest                       
  pullPolicy: IfNotPresent

replicaCount: 1


service:
  type: NodePort
  port: 3000
  nodePort: 30001

mongodb:
  enabled: true                     
  image: mongo:6.0
  port: 27017
  persistence:
    enabled: false                   
    size: 1Gi


resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

probes:
  liveness:
    path: /healthz
    initialDelaySeconds: 30
    periodSeconds: 10
  readiness:
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 5


env:
  NODE_ENV: development
  MONGODB_URL: mongodb://localhost:27017/mydb  # Kubernetes DNS for service


ingress:
  enabled: false
  className: nginx
  hosts:
    - host: myapp.local
      paths:
        - path: /
          pathType: Prefix
