apiVersion: v1
kind: Service
metadata:
  name: node-express-service
  namespace: default
spec:
  selector:
    app: node-express
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001  # Optional: Specify a port between 30000-32767
  type: NodePort
