apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-express-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-express
  template:
    metadata:
      labels:
        app: node-express
    spec:
      containers:
        - name: node-app
          image: monta2027/node-express:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "development"
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: node-express-secret
                  key: MONGODB_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: node-express-secret
                  key: JWT_SECRET
